### DISCUSSION TITLE
PackageVariant multiple Injectors issue

### DISCUSSION THREAD

**Discussion by uemk** [nephio-project/nephio#528] [Q&A] [answered]
Is there any solution to control which in-package resources are modified by PV Injectors besides only GVK matching?
I read the documentation for [PackageVariant](https://github.com/kptdev/kpt/blob/main/docs/design-docs/08-package-variant.md) but I cannot find the solution. Here is my case:
- I have two in-cluster ConfigMaps and I reference them in PV like that:
  ```yang
    injectors:
    - name: cm-overrides-1
    - name: cm-overrides-2
  ```
- In my upstream repo I also have 2 ConfigMaps (let's say `cm-1` and `cm-2`) for which I added such annotation:
  ```yang
    annotations:
      kpt.dev/config-injection: required
  ```
- I would like to inject data from in-cluster `cm-overrides-1` to in-package `cm-1` and to inject in-cluster `cm-overrides-2` to in-package `cm-2`
- what actually happens is that `cm-overrides-1` is injected to both in-package ConfigMaps: `cm-1` and `cm-2`

Is it possible to address my problem with some additional `pv` or `cm` configuration?
Thanks for any suggestions.

**Comment by kispaljr** [comment, marked as answer]
My understanding is that with the current porch version the best thing you can do is to introduce a unique `kind` (CRD) for both injection points, instead of using `ConfigMap`s. So you will end up with something like this in your cluster:
```
apiVersion: myapp.org/v1alpha1
kind: FirstKindOfParams
metadata:
  name: cm-overrides-1
# ....
---
apiVersion: myapp.org/v1alpha1
kind: SecondKindOfParams
metadata:
  name: cm-overrides-2
# ....
--- 
kind: PackageVariant
# ...
spec:
  injectors:
  - kind: FirstKindOfParams
    name: cm-overrides-1
  - kind: SecondKindOfParams
    name: cm-overrides-2
```

Having said that, IMHO what you ask for should be possible. We have multiple improvements to `PackageVariant` and porch in our mind, so there is a good chance that the definition of injection points will evolve to a point where it can support your use case without introducing new CRDs.
