### ISSUE TITLE
Unable to get into the regional cluster

### ISSUE THREAD

**Issue by praj527** [nephio-project/nephio#334]
Hi team,

I tried creating the regional cluster by following the steps mention in the following [document](https://github.com/nephio-project/docs/blob/main/user-guide/exercises.md).

I am trying this on the local VM, but I am not able to get into the regional cluster. If I missed anything, please let me know.
<img width="307" alt="image" src="https://github.com/nephio-project/nephio/assets/67963061/2bdcd592-9647-4944-b65e-0defcc1e3b98">

<img width="901" alt="image" src="https://github.com/nephio-project/nephio/assets/67963061/ab6d2876-cec2-4baf-b10e-05fb6c02bb0e">

And also can you please point me to the document, which contains the steps to remove the regional-cluster.

**Comment by praj527** [comment]
I tied recreating from scratch, it also not helped.

**Comment by praj527** [comment]
On debugging more we found that regional node container is in created state only.
Please let us know the further step to resolve the issue.

<img width="782" alt="image" src="https://github.com/nephio-project/nephio/assets/67963061/06a785bf-1041-4f76-aef9-2d09b80b8e20">

**Comment by praj527** [comment]
Hi @johnbelamaric, 
Can you please guide us for further steps to follow in order to resolve the issue. Or please point us to the troubleshooting guide which needs to be followed.

**Comment by johnbelamaric** [comment]
So, this looks like a CAPI/KinD issue. I would start with `kubectl describe` of the cluster and its machinesets and machines, and see where that leads. Are you using the recommended VM size?

Another option is to perhaps take a look at https://cluster-api.sigs.k8s.io/user/troubleshooting.html.

I suggest reaching out on the #sig-automation or #sig-release Slack channels for more interactive support than we can do on issues.

**Comment by praj527** [comment]
Thanks @johnbelamaric for the reply.
We will try to debug that out.

Here are the `kubectl` description for the Cl, Machine and MachineSet.
[cl_regional_description.txt](https://github.com/nephio-project/nephio/files/12436301/cl_regional_description.txt)
[machine_regional_description.txt](https://github.com/nephio-project/nephio/files/12436302/machine_regional_description.txt)
[machineset_regional_description.txt](https://github.com/nephio-project/nephio/files/12436303/machineset_regional_description.txt)

**Comment by praj527** [comment]
Hello @johnbelamaric
I am not able to join the slack channel `#sig-automation` or `#sig-release`, I thing invitation require for the [nephio workspace](https://nephio.slack.com/?redir=%2Farchives%2FC03L6QB2) on the slack

**Comment by praj527** [comment]
@johnbelamaric Thanks, I am able join the slack.

**Comment by electrocucaracha** [comment]
> Thanks @johnbelamaric for the reply. Yes, we are using the recommended VM size. We will try to debug that out.
> 
> Here are the `kubectl` description for the Cl, Machine and MachineSet. [cl_regional_description.txt](https://github.com/nephio-project/nephio/files/12436301/cl_regional_description.txt) [machine_regional_description.txt](https://github.com/nephio-project/nephio/files/12436302/machine_regional_description.txt) [machineset_regional_description.txt](https://github.com/nephio-project/nephio/files/12436303/machineset_regional_description.txt)

According to the description files, there is an issue with the creation of the control plane node in the regional cluster.

```yaml
Name:         regional
Namespace:    default
API Version:  cluster.x-k8s.io/v1beta1
Kind:         Cluster
Status:
  Conditions:
    Last Transition Time:  2023-08-17T13:44:05Z
    Message:               Scaling up control plane to 1 replicas (actual 0)
    Reason:                ScalingUp
    Severity:              Warning
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-08-17T13:44:04Z
    Message:               Waiting for control plane provider to indicate the control plane has been initialized
    Reason:                WaitingForControlPlaneProviderInitialized
...
---
Name:         regional-lntfk-98x48
Namespace:    default
API Version:  cluster.x-k8s.io/v1beta1
Kind:         Machine
Status:
  Bootstrap Ready:  true
  Conditions:
    Last Transition Time:  2023-08-17T13:47:06Z
    Message:               1 of 2 completed
    Reason:                BootstrapFailed
    Severity:              Warning
    Status:                False
...
---
Name:         regional-md-0-9975w-7679f64685x48lcc
Namespace:    default
API Version:  cluster.x-k8s.io/v1beta1
Kind:         MachineSet
Status:
  Conditions:
    Last Transition Time:  2023-08-17T13:44:07Z
    Message:               Scaling up MachineSet to 1 replicas (actual 0)
    Reason:                ScalingUp
    Severity:              Warning
    Status:                False
    Type:                  Ready
...
```
Regarding the HW specs of that VM, how much CPU/RAM do you have it?
