### ISSUE TITLE
nfdeployment specializer does not allow static declaration of insertion of parameterRef 

### ISSUE THREAD

**Issue by arora-sagar** [nephio-project/nephio#448]
Here is my use case, I want to deploy an `amf` workload with the following description. It contains a static entry of `parameterRef`

```yaml
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: amf-example
  namespace: amf-example
spec:
  provider: amf.openairinterface.org
  parametersRefs:
  - name: oai-amf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
```

The final workload (on which the specializer `docker.io/nephio/nfdeploy-fn:1727950412117446656` already worked). Has removed the parameterRef section

```yaml
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: amf-example/amf-example
  name: amf-regional
  namespace: oai-core
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|amf-example|amf-example'
spec:
  provider: amf.openairinterface.org
  interfaces:
  - name: n2
    ipv4:
      address: 172.2.0.254/24
      gateway: 172.2.0.1
    vlanID: 4
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  capacity:
    maxDownlinkThroughput: "0"
    maxSubscribers: 1000
    maxUplinkThroughput: "0"
```

I think we allow a statically defined NFDeployment. But for R2 we really need static parameterRef declaration. 

The issue was already raised in https://github.com/nephio-project/nephio/pull/418#issuecomment-1777132570.
