### ISSUE TITLE
Incorrect handling of non-root directory based repos in Porch

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/nephio#451]
Our [catalog](https://github.com/nephio-project/catalog) repository contains multiple sub-directories. Porch assumes a Repository (note the capital, I mean the K8s resource) is a "flat" space for holding packages. We structured the catalog Git repo with the intent to use multiple Porch repos to represent that same repository, like this:

```
apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: blueprints-infra-gcp
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: false
  git:
    branch: main
    directory: /infra/gcp
    repo: https://github.com/nephio-project/catalog.git
  type: git
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: blueprints-workloads-free5gc
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: false
  git:
    branch: main
    directory: /workloads/free5gc
    repo: https://github.com/nephio-project/catalog.git
  type: git
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: blueprints-workloads-oai
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: false
  git:
    branch: main
    directory: /workloads/oai
    repo: https://github.com/nephio-project/catalog.git
  type: git
```

That is, we have multiple Porch Repository resources, pointing to different subdirectories. In theory this is fine, but it is not a feature of Porch that is well exercised, and I am seeing some issues.

1. It is necessary for tags to include the full path. I think this is actually probably the correct behavior, since that way you have true independence across Repository objects. So, for example we must use "infra/gcp/cc-repo-csr/v1" not "cc-repo-csr/v1" as the tag.

2. Each package revision gets duplicated across all instances with the same base git repo. In other words, it sees this as duplicated repositories rather than separate repos. So with the three Repository resources registered above, we see:

```
[hi on] jbelamaric@jbelamaric:~/proj/gh/johnbelamaric/nephio$ k get packagerevisions --context gke_jbelamaric-dev_us-central1_nephio
NAME                                                            PACKAGE                              WORKSPACENAME   REVISION   LATEST   LIFECYCLE   REPOSITORY
blueprints-infra-gcp-13e9002337c2cc7a143523b47efedc7d31920f98   cc-cluster-gke-std-csr-cs            main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-336b4f189458637bca8203a06c389e0ca2c2f0af   cc-cluster-gke-std-csr-cs            v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-995246eab970328dbe08de5c06d117698d12f861   cc-repo-csr                          main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-b565038bb061184bfd04a3d33b6c5b53a5848bef   cc-repo-csr                          v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-fc58b20435dd4d14d3384466fcbedba673099ebf   nephio-blueprint-repo                main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-989f590d68008a9a3f88e39f7a563f844c48f810   nephio-blueprint-repo                v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-00b92adc8ca9e87149a60e289db96abd00290f08   nephio-workload-cluster-gke          main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-5a9ea99ed52ccc679df5698cbddd74074e1b31d2   nephio-workload-cluster-gke          v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-13e9002337c2cc7a143523b47efedc7d31920f98   cc-cluster-gke-std-csr-cs            main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-336b4f189458637bca8203a06c389e0ca2c2f0af   cc-cluster-gke-std-csr-cs            v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-995246eab970328dbe08de5c06d117698d12f861   cc-repo-csr                          main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-b565038bb061184bfd04a3d33b6c5b53a5848bef   cc-repo-csr                          v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-fc58b20435dd4d14d3384466fcbedba673099ebf   nephio-blueprint-repo                main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-989f590d68008a9a3f88e39f7a563f844c48f810   nephio-blueprint-repo                v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-00b92adc8ca9e87149a60e289db96abd00290f08   nephio-workload-cluster-gke          main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-5a9ea99ed52ccc679df5698cbddd74074e1b31d2   nephio-workload-cluster-gke          v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-13e9002337c2cc7a143523b47efedc7d31920f98   cc-cluster-gke-std-csr-cs            main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-336b4f189458637bca8203a06c389e0ca2c2f0af   cc-cluster-gke-std-csr-cs            v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-995246eab970328dbe08de5c06d117698d12f861   cc-repo-csr                          main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-b565038bb061184bfd04a3d33b6c5b53a5848bef   cc-repo-csr                          v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-fc58b20435dd4d14d3384466fcbedba673099ebf   nephio-blueprint-repo                main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-989f590d68008a9a3f88e39f7a563f844c48f810   nephio-blueprint-repo                v1              v1         true     Published   blueprints-infra-gcp
blueprints-infra-gcp-00b92adc8ca9e87149a60e289db96abd00290f08   nephio-workload-cluster-gke          main            main       false    Published   blueprints-infra-gcp
blueprints-infra-gcp-5a9ea99ed52ccc679df5698cbddd74074e1b31d2   nephio-workload-cluster-gke          v1              v1         true     Published   blueprints-infra-gcp
```

I think 1) is ok, but I am not sure if Porch properly creates tags like this. I will have to try it. I think I can fix 2) pretty quickly. But I wanted to raise this as a concern; we may want to consider breaking this out into multiple Git repos to be safe.
