### ISSUE TITLE
Duplicate entries after rendering the final NFDeployment template

### ISSUE THREAD

**Issue by arora-sagar** [nephio-project/nephio#493]
When trying the latest `nfdeploy-fn` there are duplicate entries in `parametersRefs` field. I think we should do a check in lists to avoid duplicate entries. 

```
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: smf-example/smf-example
  name: smf-regional
  namespace: free5gc-cp
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|smf-example|smf-example'
spec:
  provider: smf.free5gc.io
  interfaces:
  - name: n4
    ipv4:
      address: 172.1.1.254/24
      gateway: 172.1.1.1
    vlanID: 5
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  parametersRefs:
  - name: smf-regional-upf-edge01
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-regional-upf-edge01
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-regional-upf-edge01
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-regional-upf-edge02
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-regional-upf-edge02
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-regional-upf-edge02
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  capacity:
    maxDownlinkThroughput: "0"
    maxNFConnections: 5
    maxSessions: 500
    maxUplinkThroughput: "0"
```

__To repoduce__

Deploy free5gc smf function using R2 test-infra main branch.
