### ISSUE TITLE
Enable SIgned Releases

### ISSUE THREAD

**Issue by VedRatan** [nephio-project/nephio#553]
https://clomonitor.io/docs/topics/checks/#signed-releases-from-openssf-scorecard

See: #536

**Comment by VedRatan** [comment]
@liamfallon @johnbelamaric we can enable signed releases by following the steps mentioned over [here](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Comment by nyrahul** [comment]
We hd this discussed in the Nephio Developer Summit. 
The aim is to leverage cosign for image signign .. The flow is as follows.
![SIG-Security_ Nephio Dev Summit ](https://github.com/nephio-project/nephio/assets/9133227/60240d30-d7c1-4649-9b67-6ebb880f1010)

**Comment by PrimalPimmy** [comment]
In our project Kubearmor, we used Cosign as well in this PR:
https://github.com/kubearmor/KubeArmor/pull/1739

Here we used goreleaser and github actions, but nephio doesn't have that, so I need to understand how are releases done in Nephio. What part is automated and what part is manual?

**Comment by radoslawc** [comment]
Hi! @nyrahul and @VedRatan we're signing released images since first release using cosign just not using ephemeral keys but a fixed key. Signature is uploaded as artifact to docker hub, for example:
here's vlan-fn image for release v2.0.0:
https://hub.docker.com/repository/docker/nephio/vlan-fn/tags?page=&page_size=&ordering=&name=v2.0.0
and corresponding signature, sbom and security scan results are uploaded as artifacts 
https://hub.docker.com/repository/docker/nephio/vlan-fn/tags?page=&page_size=&ordering=&name=22e6b
with name being image sha and extensions respectively *.sig, *.sbom and *_scan.txt 
Public key is on wiki: https://wiki.nephio.org/display/HOME/Code+signing
This process is for now manual and for sure can be improved so I believe we should join our forces to work on that.

**Comment by anurag-rajawat** [comment]
Hi @radoslawc I would like to work on this.

**Comment by anurag-rajawat** [comment]
Hey @radoslawc,
Based on my understanding, to automate the image signing using cosign as part of release pipeline, we'd need to:
- Update [release.sh](https://github.com/nephio-project/test-infra/blob/main/images/releaser/release.sh) and [Dockerfile](https://github.com/nephio-project/test-infra/blob/main/images/releaser/Dockerfile) to incorporate cosign for signing the images.
- Add a separate cosign container (built in previous step) in the postsubmit jobs in [prow configs](https://github.com/nephio-project/test-infra/blob/70edb080cf5ab26051f9aeefe503e723f3d12fc5/prow/config/config.yaml#L91), something like:
```yaml
postsubmits:
  nephio-project/free5gc:
   - name: build-push-image-free5gc-operator-release-conf
     ...
     ...
      containers:
      ...
      - name: cosign
        image: ttl.sh/cosign:24h
        args:
          - nephio/free5gc-operator:${PULL_BASE_REF}
         env:
          - name: COSIGN_PRIVATE_KEY
            value: PRIVATE_KEY_VAL
          - name: COSIGN_PRIVATE_KEY_PASSWD
            value: PRIVATE_KEY_PASSWD
...
```
Is my understanding correct?
