### ISSUE TITLE
[focom] Define FocomClusterRequest CRD and create focom controller managing its lifecycle

### ISSUE THREAD

**Issue by adetalhouet** [nephio-project/nephio#763]
See design details here: https://docs.google.com/presentation/d/1iyE_XLkBJkl_ClYsE_vRnEkm8Ica7YE0/edit#slide=id.p1

In scope:
- creation of the API and the initial controller reconciling it. Here is an example CR.
  - the `clusterTempalteRef` should point to an existing `PackageVariant` from the o-cloud referenced in `ocloudRef`
```
apiVerson: focom.provisioning.oran.org
kind: FocomClusterRequest
metadata:
  name: ExampleCluster
  namespace: default
spec:
  ocloudRef: O-Cloud1
  clusterTemplateRef: ocloud1-cluster-template1
  siteRef: 
```

- controller should use the `ocloudRef` to identify the IMS endpoint to send the request to.
- controller should use the `clusterTemplateRef` field to identify the `PackageVariant` to deploy from the `ocloudRef` IMS
- controller should provide the `siteRef` to identify the target site where the cluster should be.
- controller should use `FocomClusterRequest` as the NBI, and emit a `ClusterRequest` to the IMS of the identified `ocloudRef` using the k8s api.

Out of scope: 
- Status monitoring and reporting
