### ISSUE TITLE
Add a "Porchfile" to kpt packages that stores porch-specific metadata

### ISSUE THREAD

**Issue by kispaljr** [nephio-project/nephio#783]
### TL;DR

 Add a YAML file named `Porchfile` to kpt packages managed by porch to persistently store porch-specific metadata. 

### Overview

Similarly to how kpt stores package metadata in Kptfile, porch should store its own package metadata in Porchfile. Porchfile should contain a valid KRM object, with the local-config annotation. Here is a possible example Porchfile content:
```YAML
apiVersion: porch.kpt.dev/v1
kind: Porchfile
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  name: my-kpt-package
spec:
  readinessGates:
    - req.nephio.org/v1alpha1.Interface.n3
    - workload.nephio.org/v1alpha1.NFDeployment.upf-cluster01
status:
  conditions:
  - message: update condition for initial resource
    reason: workload.nephio.org/v1alpha1.NFDeployment.upf-cluster01
    status: "False"
    type: req.nephio.org/v1alpha1.Interface.n3
  - message: update for condition
    status: "False"
    type: workload.nephio.org/v1alpha1.NFDeployment.upf-cluster01
  lastRender:
    error: ""
    result:
      exitCode: 0  
```

### What kind of metadata should be stored in Porchfile?

Let's assume that we have a kpt package in a git repository, and we have multiple porch instances running in separate Kubernetes clusters that has the same git repository registered. 

Some of the metadata belonging to the package should be always the same no matter via which porch instance we observe the package. Or, in other words, if this kind of metadata is changed via one porch instance the change should be visible in all other porch instances. Some examples for this kind of metadata: 
- description
- upstream package
- mutation pipeline
- readiness gates
- conditions
- results of the latest render operation performed by porch

These kinds of metadata should be stored either in `Kptfile` - if it is owned by kpt, or in `Porchfile` - if the data is owned by porch.

There are other kinds of package metadata that shouldn't be synchronized across porch instances, e.g.:
- owner references
- labels
- annotations

These types of package metadata should be persisted in the so-called "metadata store" that is already implemented in porch [here](https://github.com/nephio-project/porch/blob/main/pkg/meta/store.go).

Historically kpt and porch were part of the same project, so there were no need for a separate `Kptfile` and `Porchfile`. This is the reason for example that `readinessGates` and `conditions` that are only used by porch became part of Kptfile. Those two should be migrated from Kptfile to Porchfile.

#### Kptfile

A natural alternative storage for the Porchfile metadata would be the Kptfile itself. Unfortunately that would make porch-managed kpt packages incompatible with the `kpt` CLI tool. This is a problem for porch developers and users, since we still heavily utilize the kpt command for development and troubleshooting of kpt packages, e.g. to run `kpt fn render` on a local copy of a kpt package, or deploying a kpt package by `kpt live apply`.

#### Metadata store

We already established above that the porch-internal metadata store was designed to store other kinds of metadata than is proposed to be stored in a Porchfile.
