### ISSUE TITLE
porch function runner is unable to pull image from a repository with self-signed certificate

### ISSUE THREAD

**Issue by dromie** [nephio-project/nephio#819]
There is no configuration option to add a trusted private certificate authority for pulling docker images.

Mounting a configmap/secret to /etc/ssl/cert.pem does work as a workaround.

**Comment by dromie** [comment]
I've seen your PR about authentication, but this issue is about the SSL/TLS certificate of the registry.
The actual error message is "cert: x509: certificate signed by unknown authority: Get "https://<REGISTRY URL>": tls: failed to verify certificate: x509: certificate signed by unknown authority"

**Comment by Catalin-Stratulat-Ericsson** [comment]
perhaps you could try [this](https://docs.nephio.org/docs/porch/using-porch/adding-external-git-ca-bundle/)
its intended for git deployments over https but it may also work for your use case.

**Comment by Catalin-Stratulat-Ericsson** [comment]
if you could provide a step by step issue reproduction with logs that would be very helpful.

**Comment by kispaljr** [comment]
1. deploy a local container image registry (i.e. Harbor) with a self-signed TLS certificate, that is accessible e.g. at https://local-registry.my/...
2. push a KRM function into the registry: i.e. `local-registry.my/krm-fn/set-labels:1.0`
3. `porchctl rpkg init my-pkg --repository my-repo --workspace initial `
4. `porchctl rpkg pull ...`
5. edit the Kptfile and add  `local-registry.my/krm-fn/set-labels:1.0` to the pipeline, i.e.:
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: my-pkg
  annotations:
    config.kubernetes.io/local-config: "true"
pipeline:
  mutators:
  - image: local-registry.my/krm-fn/set-labels:1.0
```
6. `porchctl rpkg push ...`

the rendering of the package (that is triggered by push) will fail, because porch will be unable to pull the `local-registry.my/krm-fn/set-labels:1.0` KRM function due to "tls: failed to verify certificate: x509: certificate signed by unknown authority".
