### ISSUE TITLE
Adding token based authentication for porch repositories

### ISSUE THREAD

**Issue by Catalin-Stratulat-Ericsson** [nephio-project/nephio#866]
Just to build on the issue @efiacor raised in #741 
The secret used in the GitRepo resource should also be able to handle bearer token based authentication.
But as these secret types seem to keep increasing we need to decide whether we need to alter the GitRepo CR to accommodate for this.

A potential example would be to add a "auth-type" variable the CR so we extrapolate the logic of figuring out the type of authentication from the code logic and give that to the user to configure.
Naturally we would need to make this new variable optional to allow for backwards compatibility.
The code would also need to be altered to be able to handle these scenarios both in the logic of the different authentication types and also whether the "auth-type" variable is present or not.

e.g. 
```yaml
apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository   
metadata:  
  name: example-repo
  namespace: example-ns
spec:  
  description: example repo
  content: Package  
  deployment: false  
  type: git  
  git:    
    repo: https://example-git/example/example.git    
    directory: /    
    branch: main
    auth-type: Token # <- Example auth-type implementation, value could also be "BasicAuth" or "CaBundle" etc
    secretRef:      
      name: example-secret
```

Naturally this could also be done without any changes to the CR and simply implement logic in the code to handle bearer token based authentication and whilst this would be far quicker it would also just be leaving the problem for a later date.
