### ISSUE TITLE
ImagePullSecrets Override in kpt fn pods when using custom repositories

### ISSUE THREAD

**Issue by Catalin-Stratulat-Ericsson** [nephio-project/nephio#877]
When using custom repositories in porch the function runner is set up to add the .dockerconfigjson secret to the kpt functionn pods in the ImagePullSecrets variable.

This works as intended however there is a oversight.

The secret should only be appended if it is present in the system, however with the current implementation it overrides the entire ImagePullSecrets variable including all the secrets it could already contain and places the auth-secret in its place.

https://github.com/nephio-project/porch/blob/155acc438de7c7dfc603d17d2f746d273330cdb3/func/internal/podevaluator.go#L908-L915

what we should do is inspect the kpt-pod-template if the secret is present and if not append to the ImagePullSecrets not override.

e.g. in the current implementation if we used the pod templating on the kpt function pods to add a few other secrets to their imagePullSecrets variable they will be overridden unnecessarily and could cause problems. 

This
```yaml
spec:
  imagePullSecrets:
  - name: secret-1
  - name: secret-2
```
Will become
```yaml
spec:
  imagePullSecrets:
  - name: auth-secret
```
Instead of this

```yaml
spec:
  imagePullSecrets:
  - name: secret-1
  - name: secret-2
  - name: auth-secret
```
