### ISSUE TITLE
[BUG]: Porch Update Strategies conflict bug (copy-merge or force-delete-replace)

### ISSUE THREAD

**Issue by lapentad** [nephio-project/nephio#898]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### **Bug Report: Patch Conflict During Update with `copy-merge` or `force-delete-replace` Strategies**

![Image](https://github.com/user-attachments/assets/765bb85a-b45e-4342-9275-f4aac2b5fcc3)
This bug arise when there is a local change to a package, that differs from both its upstream and downstream.

**Command:**
```bash
porchctl rpkg update porch-test.deployment.v1 --namespace=porch-demo --revision=2
```

**Observed Error:**
```
Error: Internal error occurred: error applying patch: conflict: fragment line does not match src line
```

**Call Stack Details (partial):**
```
error(*fmt.wrapError) *{msg: "error applying patch: conflict: fragment line does not match src line", 
err: error(*github.com/bluekeyes/go-gitdiff/gitdiff.ApplyError) *{Line: 11, Fragment: 1, FragmentLine: 4, 
err: error(*com/bluekeyes/go-gitdiff/gitdiff.Conflict
```

---

### **Description**

When performing an update operation using strategies like `copy-merge` or `force-delete-replace`, a patch conflict is being triggered during validation, even though these strategies are designed to override changes and should not require a 3-way merge validation of the local, upstream, and downstream packages.

This leads to an error in the `apply` step due to patch conflict markers such as:
```
--- a.yaml
+++ a.yaml
@@ -8,7 +8,7 @@
```

---

### **Expected Behavior**

Strategies like `copy-merge` and `force-delete-replace` are intended to apply changes disruptively by overwriting or replacing package content. Therefore, patch validation (particularly diff-based conflict detection) should be bypassed for these strategies. Validation assumes the need for conflict resolution, which contradicts the semantics of these update modes.

---

### **Technical Details**

The update call stack (simplified) for a typical `porchctl rpkg update` flow:
1. `porchctl`: Executes the command and initiates a PUT request to the Kubernetes API Server.
2. **Kubernetes API Server**: Forwards the request to the Porch API server.
3. **Porch API Server**:
   - `packagecommon.updatePackageRevision`
   - `cad.UpdatePackageRevision`
     - `cad.isRecloneAndReplay` (returns `true` when cloned packages differ)
     - `cad.RecloneAndReplay`
       - `generictaskhandler.ApplyTasks`
       - `generictaskhandler.applyResourceMutations`
       - `mutation.apply`

In the presence of local and downstream changes, patch conflicts can arise, resulting in failure during `applyResourceMutations`.

---

### **Proposed Solution**

Skip or modify the patch validation logic when using non-merge strategies (`copy-merge`, `force-delete-replace`) since they are explicitly meant to override existing package content.

Error Type | skipPatchMutation | Condition Result | Outcome
-- | -- | -- | --
Conflict | false | true | Error is raised
Conflict | true | false | Error is ignored
NOT Conflict | true | true | Error is raised
NOT Conflict | false | true | Error is raised

### Steps To Reproduce

```bash
#CLEANUP for previous runs
porchctl rpkg get -A | awk 'NR>1 {print "porchctl rpkg propose-delete " $2 " --namespace=" $1 "\nporchctl rpkg delete " $2 " --namespace=" $1}' | while read -r cmd; do eval $cmd; done && rm -rf ./tmp/*

echo "@@@Create B v1"
porchctl rpkg init blueprint --namespace=porch-demo --repository=porch-test --workspace=v1
porchctl rpkg pull porch-test.blueprint.v1 --namespace=porch-demo ./tmp/local-pack-blueprint
rm ./tmp/local-pack-blueprint/README.md && \
kubectl create deployment test-dep --image=busybox --dry-run=client -o yaml > ./tmp/local-pack-blueprint/a.yaml && \
kubectl create configmap test-dep --dry-run=client -o yaml > ./tmp/local-pack-blueprint/b.yaml
porchctl rpkg push porch-test.blueprint.v1 --namespace=porch-demo ./tmp/local-pack-blueprint
echo "@@@"

echo "@@@Approve B v1"
porchctl rpkg propose porch-test.blueprint.v1 --namespace=porch-demo
porchctl rpkg approve porch-test.blueprint.v1 --namespace=porch-demo
echo "@@@"

echo "@@@Copy B v1 -> B v2, and make an update"
porchctl rpkg copy porch-test.blueprint.v1 --namespace=porch-demo --workspace=v2 --replay-strategy
porchctl rpkg pull porch-test.blueprint.v2 --namespace=porch-demo ./tmp/local-pack-blueprint2
sed -i 's/replicas: 1/replicas: 2/' ./tmp/local-pack-blueprint2/a.yaml
kubectl create deployment my-dep --image=nginx --dry-run=client -o yaml > ./tmp/local-pack-blueprint2/c.yaml
porchctl rpkg push porch-test.blueprint.v2 --namespace=porch-demo ./tmp/local-pack-blueprint2
echo "@@@"

echo "@@@Approve B v2"
porchctl rpkg propose porch-test.blueprint.v2 --namespace=porch-demo
porchctl rpkg approve porch-test.blueprint.v2 --namespace=porch-demo
echo "@@@"

echo "@@@Clone B v1 -> D v1, select Strategy"
porchctl rpkg clone porch-test.blueprint.v1 --namespace=porch-demo --repository=porch-test --workspace=v0 --strategy=copy-merge deployment

porchctl rpkg copy porch-test.deployment.v0 --namespace=porch-demo --workspace=v1 --replay-strategy
porchctl rpkg pull porch-test.deployment.v1 --namespace=porch-demo ./tmp/local-pack-deployment
kubectl create service clusterip CIQ --tcp=80:80 --dry-run=client -o yaml > ./tmp/local-pack-deployment/cIQ.yaml && \
kubectl create secret generic test-val --dry-run=client -o yaml > ./tmp/local-pack-deployment/day0value.yaml
sed -i 's/replicas: 1/replicas: 3/' ./tmp/local-pack-deployment/a.yaml
porchctl rpkg push porch-test.deployment.v1 --namespace=porch-demo ./tmp/local-pack-deployment
echo "@@@"

porchctl rpkg update --discover=upstream

echo "porchctl rpkg update porch-test.deployment.v1 --namespace=porch-demo --revision=2"

porchctl rpkg update porch-test.deployment.v1 --namespace=porch-demo --revision=2

porchctl rpkg propose porch-test.deployment.v1 --namespace=porch-demo
porchctl rpkg approve porch-test.deployment.v1 --namespace=porch-demo

#######################
echo "@@@ FORCE DELETE REPLACE @@@"


porchctl rpkg copy porch-test.blueprint.v2 --namespace=porch-demo --workspace=v3
porchctl rpkg pull porch-test.blueprint.v3 --namespace=porch-demo ./tmp/local-pack-blueprint3
sed -i 's/replicas: 2/replicas: 5/' ./tmp/local-pack-blueprint3/a.yaml
rm ./tmp/local-pack-blueprint3/b.yaml
porchctl rpkg push porch-test.blueprint.v3 --namespace=porch-demo ./tmp/local-pack-blueprint3
porchctl rpkg propose porch-test.blueprint.v3 --namespace=porch-demo
porchctl rpkg approve porch-test.blueprint.v3 --namespace=porch-demo



porchctl rpkg clone porch-test.blueprint.v1 --namespace=porch-demo --repository=porch-test --workspace=v1 --strategy=force-delete-replace deletereplace
porchctl rpkg pull porch-test.deletereplace.v1 --namespace=porch-demo ./tmp/local-pack-delete
sed -i 's/replicas: 1/replicas: 11/' ./tmp/local-pack-delete/a.yaml
porchctl rpkg push porch-test.deletereplace.v1 --namespace=porch-demo ./tmp/local-pack-delete

porchctl rpkg update --discover=upstream
echo "porchctl rpkg update porch-test.deletereplace.v1 --namespace=porch-demo --revision=3"
porchctl rpkg update porch-test.deletereplace.v1 --namespace=porch-demo --revision=3


porchctl rpkg propose porch-test.deletereplace.v1 --namespace=porch-demo
porchctl rpkg approve porch-test.deletereplace.v1 --namespace=porch-demo



echo "deletereplace should have only a.yaml c.yaml and a.spec.replicas=5"
echo "deployment should have a b c ciq da0values and a.spec.replicas=2"
```

**Comment by lapentad** [comment]
After investigation the root cause was found in `porchctl`
During the update scenario the upstream reference was being passed to the object as a reference, when this reference was changing during the update also the reference would update, and effectively losing the original reference of the clone upstream

An example, based on the script from before:
1. A Deployment v1 was cloned from Blueprint v1
2. Blueprint v2 was copied and approved
3. Deployment v1 can be updated to the second revision of Blueprint

The issue is that after the approval `spec.tasks.clone.upstreamRef.name` was changing

[Adding a copy of that object solved the issue also seen in the update conflict ](https://github.com/nephio-]project/porch/pull/223/files#diff-fb1ee3dc7b76e7049faeaf6752180426ca49b12a26ec6ad6c3a7ead6fdc32c42R162)

```
#OLD VERSION OF PORCHCTL
porchctl rpkg get -n porch-demo porch-test.deployment.v1 -o yaml
apiVersion: porch.kpt.dev/v1alpha1
kind: PackageRevision
...
spec:
  lifecycle: Published
  packageName: deployment
  repository: porch-test
  revision: -1
  tasks:
  - clone:
      strategy: copy-merge
      upstreamRef:
        upstreamRef:
          name: porch-test.blueprint.v2
...
  - type: update
    update:
      upstreamRef:
        upstreamRef:
          name: porch-test.blueprint.v2
...

#NEW VERSION OF PORCHCTL
.build/porchctl rpkg get -n porch-demo porch-test.deployment.v1 -o yaml
apiVersion: porch.kpt.dev/v1alpha1
kind: PackageRevision
...
spec:
  lifecycle: Published
  packageName: deployment
  repository: porch-test
  revision: 1
  tasks:
  - clone:
      strategy: copy-merge
      upstreamRef:
        upstreamRef:
          name: porch-test.blueprint.v1
    type: clone
...
  - type: update
    update:
      upstreamRef:
        upstreamRef:
          name: porch-test.blueprint.v2
...
```
