### ISSUE TITLE
[BUG]: FluxCD Doc PVs fail

### ISSUE THREAD

**Issue by dkosteck** [nephio-project/nephio#938]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the bug

The current [docs](https://docs.nephio.org/docs/guides/user-guides/usecase-user-guides/exercise-3-fluxcd-wl/) have PVs that reference `spec/upstream/revision: main` but that causes an error when applying: `The PackageVariant "flux-regional-cluster" is invalid: spec.upstream.revision: Invalid value: "string": spec.upstream.revision in body must be of type integer: "string"`

It looks like in the [flux tests](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/flux/002-free5gc-cp.yaml) the new reference should be `workspaceName`

### Steps To Reproduce

```
cat << EOF | kubectl apply -f - 
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: flux-regional-cluster
spec:
  upstream:
    repo: catalog-infra-capi
    package: nephio-workload-cluster-flux
    revision: main
  downstream:
    repo: mgmt
    package: regional
  annotations:
    approval.nephio.org/policy: initial
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-labels:v0.2.0
      configMap:
        nephio.org/site-type: regional
        nephio.org/region: us-west1
EOF
```
